# Example buildspec.yml
version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - echo Installing dependencies
      - pip install -r requirements.txt
  build:
    commands:
      - echo Running tests
      - pytest
  post_build:
    commands:
      - echo Build completed on `date`

